### ISSUE TITLE
Not needed appends and if statements

### ISSUE THREAD

**Issue by snowthesprite** [RavenHex1296/machine-learning#5]
While this is completely optional it is something I see people do a lot. Its just a really small thing that for me, makes it a little easier to see what's in what. Its just that in sections where you have something like `if index == 0`, and then the rest just continues on as normal, you could just initialize the list or dictionary with the element. That gets rid of the extra if statement, and something that both you and the computer have to keep track of. The biggest example I can see right away in most codes is the linear_regressor, when your making the coefficents dict. When stating the dict, you can write:

 coefficients_dict = {'constant' : coefficients.elements[0][0]}

and that would save you the if else statement in the range function. As that first element is out of the way, you could either set your range to start at 1 (`range(1, len(indpendent_variables) + 1)`), or you could spread out that +1 so that you get:

for n in range(len(indpendent_variables)):
            coefficients_dict[indpendent_variables[n]] = coefficients.elements[n + 1][0]

These are really just small changes. Your code looks really good in general!

**Comment by RavenHex1296** [comment]
Thnaks! That helps out a lot. I'll keep that in mind (hopefully) for future assignments where we are working with dictionaries
